Message.destroy_all()
Subscription.destroy_all()
PostTag.destroy_all()
Tag.destroy_all()
Post.destroy_all()
Channel.destroy_all()
User.destroy_all()

u1 = User.create(username: "Somaia", password_digest: "guest", bio: "Cracking skulls with mad code skills all the way from the UAE to the USA", img_url: "https://ca.slack-edge.com/T02MD9XTF-UT57884MV-8720f9540343-512")
u2 = User.create(username: "DrVonDevious", password_digest: "guest", bio: "Existence is suffering, so you might as well use Vim", img_url: "https://ca.slack-edge.com/T02MD9XTF-UT02BHX47-1e2b6e51a86d-512")
u3 = User.create(username: "SaintRobDub", password_digest: "guest", bio: "Locksmith turned coder, so now I can break into your computer AND your house", img_url: "https://ca.slack-edge.com/T02MD9XTF-USLN1N0SX-639efefc59a2-512")


c1 = Channel.create(name: "General", description:"everything youcould ever want to know about foobar", img:"https://logos.flamingtext.com/Word-Logos/general-design-sketch-name.png")
c2 = Channel.create(name: "Locksmithing",description:"everything youcould ever want to know about foobar" ,img:"https://lh3.googleusercontent.com/proxy/m5d_tSOR6aV608VLdYPioF-Atklm-DHeovSIXpWHc5Z0x-gK5jB1hOlAcaIPfC17exZ2zOX2LA4Q9lxsS3f0EB_uM8P78NdnN4AhFsxip680k9ajyPc2ivYP2BxwbqDuLam9HTWcWP9ztQ3t4nU2NPRv2Q")
c3 = Channel.create(name: "Coding",description:"everything youcould ever want to know about foobar", img:"https://images.wallpaperscraft.com/image/code_programming_text_140050_1350x2400.jpg")
c4 = Channel.create(name: "Livestock",description:"everything youcould ever want to know about foobar", img:"https://media.pri.org/s3fs-public/styles/story_main/public/story/images/6549384291_ddd1396526_b.jpg?itok=derKhZ7A")


p1 = Post.create(title: "First Post", body: "Hello World!", channel_id: c1.id, user_id: u1.id)
p2 = Post.create(title: "Second Post", body: "Almost as good as the first", channel_id: c1.id, user_id: u2.id)
p3 = Post.create(title: "Third Post", body: "Quality Dropping Dramatically", channel_id: c1.id, user_id: u3.id)
p4 = Post.create(title: "Why Cows are Better than Pigs", body: "Because pigs are disgusting. THE END", channel_id: c4.id, user_id:u1.id)
p5 = Post.create(title: "Geese?", body: "Are geese technically livestock? What about cats?", channel_id: c4.id,user_id: u3.id)
p6 = Post.create(title: "Thoughts about Bloggins", body: "Kenny Bloggins's hit song 'Stairway to Danger Zone: italics or strong' is the best ever", channel_id: c1.id, user_id: u2.id)
p7 = Post.create(title: "Locks and Noses", body: "You can pick both at work while you are a locksmith! Call me today at 555-555-5555", channel_id: c2.id, user_id: u3.id)

t1 = Tag.create(name: "You're It")
t2 = Tag.create(name: "No, you're It")
t3 = Tag.create(name: "Computer Debuggery")
t4 = Tag.create(name: "Unusual")

PostTag.create(post_id: p1.id, tag_id: t1.id)
PostTag.create(post_id: p2.id, tag_id: t1.id)
PostTag.create(post_id: p3.id, tag_id: t1.id)
PostTag.create(post_id: p4.id, tag_id: t1.id)
PostTag.create(post_id: p5.id, tag_id: t1.id)
PostTag.create(post_id: p6.id, tag_id: t1.id)
PostTag.create(post_id: p7.id, tag_id: t1.id)
PostTag.create(post_id: p1.id, tag_id: t2.id)
PostTag.create(post_id: p2.id, tag_id: t2.id)
PostTag.create(post_id: p3.id, tag_id: t2.id)
PostTag.create(post_id: p4.id, tag_id: t4.id)
PostTag.create(post_id: p2.id, tag_id: t3.id)
PostTag.create(post_id: p3.id, tag_id: t3.id)
PostTag.create(post_id: p2.id, tag_id: t4.id)
PostTag.create(post_id: p7.id, tag_id: t4.id)

Subscription.create(channel_id: c4.id, user_id: u1.id)
Subscription.create(channel_id: c4.id, user_id: u3.id)
Subscription.create(channel_id: c3.id, user_id: u1.id)
Subscription.create(channel_id: c3.id, user_id: u2.id)
Subscription.create(channel_id: c3.id, user_id: u3.id)
Subscription.create(channel_id: c2.id, user_id: u3.id)
Subscription.create(channel_id: c2.id, user_id: u2.id)
Subscription.create(channel_id: c1.id, user_id: u1.id)
Subscription.create(channel_id: c1.id, user_id: u2.id)

Message.create(user_id: u1.id, recipient_user_id: u2.id, content: "Hi Caleb!")
Message.create(user_id: u2.id, recipient_user_id: u1.id, content: "Hi Somaia :-(")
Message.create(user_id: u1.id, recipient_user_id: u2.id, content: "Why the frown?")
Message.create(user_id: u2.id, recipient_user_id: u1.id, content: "Paul made me watch him shave his beard")
Message.create(user_id: u2.id, recipient_user_id: u1.id, content: "I'm scarred forever now")
Message.create(user_id: u3.id, recipient_user_id: u1.id, content: "You are the best")
Message.create(user_id: u1.id, recipient_user_id: u3.id, content: "No you!")
Message.create(user_id: u3.id, recipient_user_id: u1.id, content: "You're right...")
Message.create(user_id: u2.id, recipient_user_id: u1.id, content: "Let's code the game of life")
Message.create(user_id: u3.id, recipient_user_id: u1.id, content: "I'm in")
Message.create(user_id: u3.id, recipient_user_id: u1.id, content: ":thumbsup:")
